Repository visual-decaf/decaf-compiler, pull requests merged in 2023-07, with the labels that each got.

#17 编写数学表达式计算器
  CMakeLists.txt
  parser/parser_impl.yy
  scanner/CMakeLists.txt
  scanner/scanner.cpp
  scanner/scanner.h
  scanner/scanner_impl.l
  tests/CMakeLists.txt
  tests/scanner/CMakeLists.txt
  tests/scanner/scanner_test.cpp
  tests/simple_driver.cpp
  token/CMakeLists.txt
  token/token.cpp
  token/token.h
Labels: help wanted, learning

#20 实现数学表达式AST和Parser
  CMakeLists.txt
  apis/serializable.h
  ast/CMakeLists.txt
  ast/expr.cpp
  ast/expr.h
  basic/CMakeLists.txt
  basic/ast_basic.h
  basic/parser_basic.h
  parser/CMakeLists.txt
  parser/parser.cpp
  parser/parser.h
  parser/parser_impl.yy
  tests/CMakeLists.txt
  tests/parser/CMakeLists.txt
  tests/parser/parser_test.cpp
  tests/simple_driver.cpp
  token/CMakeLists.txt
Labels: help wanted

#21 字节码与编译器实现
  CMakeLists.txt
  byte_code/CMakeLists.txt
  byte_code/byte_code.cpp
  byte_code/byte_code.h
  byte_code/byte_code_visitor.cpp
  byte_code/byte_code_visitor.h
  compiler/CMakeLists.txt
  compiler/compiler.cpp
  compiler/compiler.h
  compiler/program.cpp
  compiler/program.h
  tests/CMakeLists.txt
  tests/compiler/CMakeLists.txt
  tests/compiler/compiler_test.cpp
Labels: help wanted

#23 表达式Virtual Machine开发
  CMakeLists.txt
  byte_code/CMakeLists.txt
  byte_code/byte_code.h
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_driver.h
  byte_code/byte_code_visitor.cpp
  byte_code/byte_code_visitor.h
  program/program.h
  tests/CMakeLists.txt
  tests/vm/CMakeLists.txt
  tests/vm/vm_test.cpp
  vm/CMakeLists.txt
  vm/vm.cpp
  vm/vm.h
Labels: help wanted

#24 AST节点IntConstant继承出错
  ast/expr.h
Labels: bug

#25 修复单元测试名称错误
  tests/compiler/compiler_test.cpp
Labels: bug

#28 修改代码格式化规则
  .clang-format
  compiler/compiler.cpp
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  tests/simple_driver.cpp
  tests/vm/vm_test.cpp
  token/token.cpp
Labels: enhancement

#27 Decaf基本CLI
  CMakeLists.txt
  cli/CMakeLists.txt
  cli/decaf.cpp
  meta/version.h.in
  scanner/scanner.cpp
  scanner/scanner.h
  scanner/scanner_impl.l
Labels: enhancement

#30 添加新数学运算符（%）
  ast/expr.h
  byte_code/byte_code.h
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_visitor.h
  compiler/compiler.cpp
  parser/parser_impl.yy
  scanner/scanner_impl.l
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  tests/vm/vm_test.cpp
  vm/vm.cpp
  vm/vm.h
Labels: enhancement

#34 添加boost.log | 在cmake中使用imported target
  CMakeLists.txt
  apis/CMakeLists.txt
Labels: enhancement

#36 添加算数组合
  ast/expr.cpp
  ast/expr.h
  basic/ast_basic.h
  compiler/compiler.cpp
  compiler/compiler.h
  parser/parser_impl.yy
  scanner/scanner_impl.l
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  token/token.cpp
Labels: enhancement

#31 Int类型常量池
  byte_code/byte_code.h
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_visitor.h
  compiler/compiler.cpp
  program/CMakeLists.txt
  program/constant_pool.cpp
  program/constant_pool.h
  program/program.cpp
  program/program.h
  tests/compiler/compiler_test.cpp
  vm/vm.cpp
  vm/vm.h
Labels: enhancement

#38 使用智能指针存储AST语法树
  ast/expr.cpp
  ast/expr.h
  cli/decaf.cpp
  compiler/compiler.cpp
  compiler/compiler.h
  parser/parser.h
  parser/parser_impl.yy
  tests/ast/ast_test.cpp
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
  tests/simple_driver.cpp
Labels: bug

#32 实现反汇编器
  byte_code/CMakeLists.txt
  byte_code/byte_code.cpp
  byte_code/byte_code.h
  byte_code/byte_code_visitor.cpp
  byte_code/byte_code_visitor.h
  byte_code/disassembler/CMakeLists.txt
  byte_code/disassembler/disassembler.cpp
  byte_code/disassembler/disassembler.h
  tests/CMakeLists.txt
  tests/ast/ast_test.cpp
  tests/byte_code/CMakeLists.txt
  tests/byte_code/byte_code_test.cpp
  tests/disassembler/CMakeLists.txt
  tests/disassembler/disassembler_test.cpp
Labels: enhancement

#35 错误记录与处理
  ast/expr.cpp
  ast/expr.h
  parser/parser.cpp
  parser/parser.h
  parser/parser_impl.yy
  scanner/scanner.cpp
  scanner/scanner.h
  scanner/scanner_impl.l
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  token/token.cpp
Labels: enhancement

#42 删除五零原则的生命周期函数
  ast/expr.h
Labels: bug

#41 使用override表达更清晰的语义
  ast/expr.h
Labels: enhancement

#45 提供表达式序列化默认实现
  ast/expr.h
Labels: enhancement

#48 补充要求：scanner单元测试必须无错误
  tests/scanner/scanner_test.cpp
Labels: enhancement

#49 补充要求：parser单元测试必须无错误
  tests/parser/parser_test.cpp
Labels: enhancement

#47 添加二元逻辑运算符
  CMakeLists.txt
  ast/expr.cpp
  ast/expr.h
  basic/ast_basic.h
  byte_code/byte_code.h
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_visitor.h
  byte_code/disassembler/disassembler.cpp
  byte_code/disassembler/disassembler.h
  cli/decaf.cpp
  compiler/compiler.cpp
  compiler/compiler.h
  parser/parser_impl.yy
  scanner/scanner_impl.l
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  tests/vm/vm_test.cpp
  vm/vm.cpp
  vm/vm.h
Labels: enhancement

#46 合并常量池类型
  compiler/compiler.cpp
  program/constant_pool.cpp
  program/constant_pool.h
  program/program.cpp
  program/program.h
  tests/compiler/compiler_test.cpp
  vm/vm.cpp
Labels: enhancement

#52 添加Parser单元测试类型要求
  tests/parser/parser_test.cpp
Labels: enhancement

#51 添加程序获取结果类型接口
  program/program.cpp
  program/program.h
  tests/compiler/compiler_test.cpp
Labels: enhancement

#57 添加parser实现图的生成目标
  CMakeLists.txt
Labels: enhancement

#54 为Bool类型添加Compiler的单元测试类型要求
  tests/compiler/compiler_test.cpp
Labels: enhancement

#53 为Bool类型添加Parser单元测试类型要求
  tests/parser/parser_test.cpp
Labels: enhancement

#56 实现算数一元减法
  CMakeLists.txt
  ast/expr.cpp
  ast/expr.h
  basic/ast_basic.h
  byte_code/byte_code.h
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_visitor.h
  byte_code/disassembler/disassembler.cpp
  byte_code/disassembler/disassembler.h
  compiler/compiler.cpp
  compiler/compiler.h
  parser/parser_impl.yy
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
  tests/vm/vm_test.cpp
  vm/vm.cpp
  vm/vm.h
Labels: enhancement, good first issue, help wanted

#58 使用更直观的字符串表示token
  parser/parser_impl.yy
Labels: enhancement, good first issue

#40 实现program序列化
  ast/expr.cpp
  byte_code/byte_code.h
  program/CMakeLists.txt
  program/constant_pool.cpp
  program/constant_pool.h
  program/program.cpp
  program/program.h
  tests/CMakeLists.txt
  tests/ast/ast_test.cpp
  tests/program/CMakeLists.txt
  tests/program/program_test.cpp
  tests/type/CMakeLists.txt
  tests/type/type_test.cpp
  type/CMakeLists.txt
  type/type.cpp
  type/type.h
Labels: enhancement

#61 实现二元关系运算符
  ast/expr.cpp
  ast/expr.h
  basic/ast_basic.h
  byte_code/byte_code.h
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_visitor.h
  byte_code/disassembler/disassembler.cpp
  byte_code/disassembler/disassembler.h
  compiler/compiler.cpp
  compiler/compiler.h
  parser/parser_impl.yy
  scanner/scanner_impl.l
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  tests/vm/vm_test.cpp
  vm/vm.cpp
  vm/vm.h
Labels: enhancement

#63 检查Visitor的访问情况
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_driver.h
  byte_code/byte_code_visitor.h
  byte_code/disassembler/disassembler.cpp
  byte_code/disassembler/disassembler.h
  vm/vm.cpp
  vm/vm.h
Labels: enhancement, good first issue

#62 为虚拟机添加类型支持
  tests/vm/vm_test.cpp
  type/type.h
  vm/vm.cpp
  vm/vm.h
Labels: enhancement, good first issue, help wanted

#64 补充实现AST序列化
  ast/expr.cpp
  ast/expr.h
  tests/ast/ast_test.cpp
Labels: enhancement

#65 重构类名Token、TokenStream、Serializable
  apis/serializable.h
  ast/expr.h
  byte_code/byte_code.h
  parser/parser.h
  program/constant_pool.h
  program/program.h
  scanner/scanner.cpp
  scanner/scanner.h
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  tests/token/token_test.cpp
  token/token.cpp
  token/token.h
  token/token_stream.cpp
  token/token_stream.h
  type/type.h
Labels: bug

#66 实现相等二元运算符
  ast/expr.cpp
  ast/expr.h
  basic/ast_basic.h
  byte_code/byte_code.h
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_visitor.h
  byte_code/disassembler/disassembler.cpp
  byte_code/disassembler/disassembler.h
  compiler/compiler.cpp
  compiler/compiler.h
  parser/parser_impl.yy
  scanner/scanner_impl.l
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  tests/vm/vm_test.cpp
  vm/vm.cpp
  vm/vm.h
Labels: enhancement

#70 重构VirtualMachine
  vm/vm.cpp
  vm/vm.h
Labels: enhancement

#68 补充Token类型映射
  token/token.cpp
Labels: bug

#71 添加ByteCodeDriver汇报错误接口
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_driver.h
Labels: enhancement

#69 添加浮点数类型
  ast/expr.cpp
  ast/expr.h
  basic/ast_basic.h
  byte_code/byte_code.h
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_visitor.h
  byte_code/disassembler/disassembler.cpp
  byte_code/disassembler/disassembler.h
  cli/decaf.cpp
  compiler/compiler.cpp
  compiler/compiler.h
  parser/parser.cpp
  parser/parser_impl.yy
  program/constant_pool.cpp
  program/constant_pool.h
  program/program.cpp
  program/program.h
  scanner/scanner_impl.l
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  tests/type/type_test.cpp
  tests/vm/vm_test.cpp
  type/type.cpp
  type/type.h
  vm/vm.cpp
  vm/vm.h
Labels: enhancement

#72 启用LAC生成更详细的语法错误
  parser/parser_impl.yy
Labels: enhancement

#73 改用更强大的IELR文法
  parser/parser_impl.yy
Labels: enhancement

#76 实现浮点数节点序列化
  ast/expr.cpp
  ast/expr.h
  tests/ast/ast_test.cpp
  token/token.cpp
Labels: enhancement

#78 加入表达式语句
  ast/CMakeLists.txt
  ast/stmt.cpp
  ast/stmt.h
  basic/ast_basic.h
  byte_code/byte_code.h
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_visitor.h
  byte_code/disassembler/disassembler.cpp
  byte_code/disassembler/disassembler.h
  compiler/compiler.cpp
  compiler/compiler.h
  parser/parser.h
  parser/parser_impl.yy
  scanner/scanner_impl.l
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  tests/vm/vm_test.cpp
  type/type.h
  vm/vm.cpp
  vm/vm.h
Labels: enhancement, good first issue

#80 添加运行时栈信息
  CMakeLists.txt
  runtime/CMakeLists.txt
  runtime/stack_item/CMakeLists.txt
  runtime/stack_item/bool_stack_item.cpp
  runtime/stack_item/bool_stack_item.h
  runtime/stack_item/float_stack_item.cpp
  runtime/stack_item/float_stack_item.h
  runtime/stack_item/int_stack_item.cpp
  runtime/stack_item/int_stack_item.h
  runtime/stack_item/stack_item.cpp
  runtime/stack_item/stack_item.h
  runtime/stack_item/stack_items.h
  type/type.cpp
  type/type.h
Labels: enhancement, good first issue

#82 修复BoolStackItem未实现LOGIC_NOT的错误
  runtime/stack_item/bool_stack_item.cpp
  runtime/stack_item/bool_stack_item.h
Labels: bug

#79 实现PRINT语句
  ast/stmt.cpp
  ast/stmt.h
  basic/ast_basic.h
  byte_code/byte_code.h
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_visitor.h
  byte_code/disassembler/disassembler.cpp
  byte_code/disassembler/disassembler.h
  compiler/compiler.cpp
  compiler/compiler.h
  parser/parser_impl.yy
  scanner/scanner_impl.l
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  tests/vm/vm_test.cpp
  vm/vm.cpp
  vm/vm.h
Labels: enhancement, good first issue, help wanted

#85 修复HEX_INTEGER未使用16进制转换的错误
  parser/parser.cpp
  tests/parser/parser_test.cpp
Labels: bug

#88 重构表达式序列化数据结构
  ast/expr.cpp
  tests/ast/ast_test.cpp
Labels: enhancement

#87 添加符号表SymbolTable
  runtime/CMakeLists.txt
  runtime/symbol_table/CMakeLists.txt
  runtime/symbol_table/symbol_table.cpp
  runtime/symbol_table/symbol_table.h
Labels: enhancement

#92 添加字符串字面量
  ast/expr.cpp
  ast/expr.h
  basic/ast_basic.h
  byte_code/byte_code.h
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_visitor.h
  byte_code/disassembler/disassembler.cpp
  byte_code/disassembler/disassembler.h
  compiler/compiler.cpp
  compiler/compiler.h
  parser/parser.cpp
  parser/parser_impl.yy
  program/constant_pool.cpp
  program/constant_pool.h
  program/program.cpp
  program/program.h
  runtime/stack_item/CMakeLists.txt
  runtime/stack_item/stack_item.h
  runtime/stack_item/stack_items.h
  runtime/stack_item/string_stack_item.cpp
  runtime/stack_item/string_stack_item.h
  scanner/scanner_impl.l
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  tests/vm/vm_test.cpp
  type/type.h
  vm/vm.cpp
  vm/vm.h
Labels: enhancement

#90 变量接受可选的初始化器
  ast/stmt.h
  compiler/compiler.cpp
  parser/parser_impl.yy
  tests/compiler/compiler_test.cpp
  tests/parser/parser_test.cpp
Labels: enhancement

#94 添加IF条件判断语句
  ast/stmt.cpp
  ast/stmt.h
  basic/ast_basic.h
  byte_code/byte_code.cpp
  byte_code/byte_code.h
  byte_code/byte_code_driver.cpp
  byte_code/byte_code_driver.h
  byte_code/byte_code_visitor.h
  byte_code/disassembler/disassembler.cpp
  byte_code/disassembler/disassembler.h
  compiler/compiler.cpp
  compiler/compiler.h
  parser/parser_impl.yy
  program/program.h
  scanner/scanner_impl.l
  tests/compiler/compiler_test.cpp
  tests/decaf_source.decaf
  tests/parser/parser_test.cpp
  tests/scanner/scanner_test.cpp
  tests/vm/vm_test.cpp
  vm/vm.cpp
  vm/vm.h
Labels: enhancement

#95 忽略\r
  scanner/scanner_impl.l
Labels: bug

#97 补充字节码十六进制形式序列化
  program/program.cpp
  program/program.h
  tests/program/program_test.cpp
Labels: enhancement

#96 修复StringStackItem未序列化的错误
  runtime/stack_item/string_stack_item.cpp
  runtime/stack_item/string_stack_item.h
  tests/stack_item/stack_item_test.cpp
Labels: bug

#98 重构AST序列化格式
  apis/visual_decaf.cpp
  ast/expr.cpp
  ast/stmt.cpp
  tests/ast/ast_test.cpp
Labels: enhancement

#99 更新版本号
  CMakeLists.txt
Labels: enhancement

#101 修复Print语句序列化的错误
  CMakeLists.txt
  apis/visual_decaf.cpp
  apis/visual_decaf.h
  ast/stmt.cpp
  tests/CMakeLists.txt
  tests/ast/ast_test.cpp
  tests/simple_driver.cpp
Labels: bug
